WorkWithKOTE/Controllers/BuyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WorkWithKOTE.Models;
namespace WorkWithKOTE.Controllers
{

    public class BuyController : Controller
    {
        //
        // GET: /Buy/
        TourContext db = new TourContext();
        public ActionResult Index(int id )
        {
            Tour data = db.Tour.Find(id);
            ViewBag.TourPrices = data.Cost;
            Trip trip = new Trip();
            trip.TourId = data.TourId;
            trip.TourPrice = data.Cost;
            ViewBag.DateTourId = new SelectList(db.DateTours.Where(m => m.TourId == id), "DateTourId", "FirstDate");
            return View(trip);
        }
        [HttpPost]
        public ActionResult Index(Trip model)
        {
            db.Entry(model).State = EntityState.Added;
            db.SaveChanges();
            return RedirectToAction("Index","Home");
        }
        public ActionResult DopPricePartial(int id = 0)
        {
            var data = db.DopUslugs.Where(m=>m.TourId == id);
            
            return View(data);
        }

    }
}

WorkWithKOTE/Controllers/HomeController.cs
using DotNetOpenAuth.OpenId.Extensions.SimpleRegistration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.WebData;
using WorkWithKOTE.Filters;
using WorkWithKOTE.Models;

namespace WorkWithKOTE.Controllers
{
    [InitializeSimpleMembership]
    public class HomeController : Controller
    {
        TourContext db = new TourContext();
        public ActionResult Index()
        {
            var roles = (SimpleRoleProvider)Roles.Provider;

            //Получаем провайдер членства
            var membership = (SimpleMembershipProvider)Membership.Provider;

            // Если нет в системе роли admin, создаём её
            if (!roles.RoleExists("Admin"))
                roles.CreateRole("Admin");

            // Если нет в системе пользователя admin, создаём его(в этом месте ошибка)
            if (membership.GetUser("LevitskiyOrange@gmail.com", false) == null)
            {
                membership.CreateUserAndAccount("LevitskiyOrange@gmail.com", "123654789");
            }

            // Если у пользователя admin нет роли admin, присваиваем ему эту роль
            if (!roles.IsUserInRole("LevitskiyOrange@gmail.com","Admin"))
                roles.AddUsersToRoles(new[] { "LevitskiyOrange@gmail.com" }, new[] { "Admin" });

            return View();
        }
        public ActionResult TourForHight()
        {
            string k = "Вверх";
            string n = "Превью блока";
            var data = db.Tour.Where(m => m.TypeOfTour == k).Where(m=>m.TourStatus == n);
            return PartialView(data);
           
        }
        public ActionResult Center()
        {
            string k = "Середина";
            var data = db.Tour.Where(m => m.TypeOfTour == k);
                return PartialView(data);
        }
        public ActionResult TourForDown()
        {
            string k = "Низ";
            var data = db.Tour.Where(m => m.TypeOfTour == k);
            return PartialView(data);
        }
        public ActionResult DateForCurrentTour(int id)
        {
            
            var date = db.DateTours.Where(m => m.TourId== id);
          
            return PartialView(date);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";
            
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WorkWithKOTE/Controllers/TourDisplayController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WorkWithKOTE.Models;
namespace WorkWithKOTE.Controllers
{
    public class TourDisplayController : Controller
    {
        //
        // GET: /TourDisplay/
        TourContext db = new TourContext();
        public ActionResult Index(int id=0)
        {
            var data = db.Tour.Find(id);
            if(data.IsBus)
             ViewBag.Message = "Автобус"; 
            if(data.IsAriplane)
             ViewBag.Message1 = "Авиалинии"; 
            if (data.IsShip)
             ViewBag.Message2 = "Лайнером"; 
            return View(data);
        }
        public ActionResult DatePartial(int id)
        {

            var date = db.DateTours.Where(m => m.TourId == id);

            return PartialView(date);
        }
        public ActionResult DopUsluga(int id)
        {

            var date = db.DopUslugs.Where(m => m.TourId == id);

            return PartialView(date);
        }
        public ActionResult Teg(int id)
        {

            var date = db.Teg.Where(m => m.TourId == id);
            string file_path = Server.MapPath("~/Files/PDFIcon.pdf");
            return PartialView(date);
        }
        public ActionResult FileDownload(int id)
        {
            var data = db.Tour.Find(id);
            string file_path = data.Document;
            string file_name = Path.GetFileName(file_path);
            string extension = "application/octet-stream";
            return File(file_path,extension,file_name );
        }
      
    }
}

WorkWithKOTE/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

WorkWithKOTE/Views/Home/Center.cshtml
@model IEnumerable<WorkWithKOTE.Models.Tour>
@foreach (var item in Model)
{
    @Html.DisplayFor(m => item.NameTour)<br />
    <img src="@Html.DisplayFor(m=>item.TourImg)" width="50px" height="75px" />
    Html.RenderAction("DateForCurrentTour", new { id = item.TourId });<br />
    @Html.ActionLink("Посмотреть детали тура", "Index", "TourDisplay", new { id = item.TourId }, null)<br />
    <input type="button" value="Оплатить тур" onclick="location.href='@Url.Action("Index", "Buy", new {id=item.TourId })'" />

}

WorkWithKOTE/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

WorkWithKOTE/Views/Home/DateForCurrentTour.cshtml
@model IEnumerable<WorkWithKOTE.Models.DateTour>

@foreach (var item in Model)
{
    <p>
       Дата отправки @Html.DisplayFor(m => item.FirstDate) 
       Дата приезда @Html.DisplayFor(m => item.SecondDate)
    </p>
} 

WorkWithKOTE/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
        <div id="big-preview-img" class="clearfix">
            <div class="wish">
                <img id="big-logo" src="~/Content/img/big-logo.png" class="image" />

                <p id="wishletter">
                    <span id="textspan">Я хочу...<br /></span><span id="textspan1">Тур в Карпаты из Днепропетровска</span>
                </p>

                <div class="buttons clearfix">
                    <a href="#" class="yes-btn">
                        <span id="textspan2">Да,</span><span id="textspan3"> </span><span id="textspan4">Я хочу&#x21;</span>
                    </a>
                    <a href="#" class="no-btn">
                        <span id="textspan5">Нет,</span><span id="textspan6"> </span><span id="textspan7">что-то другое</span>
                    </a>
                </div>
            </div>
            <div class="scroll clearfix">
                <p class="scroll-text"> Скроль<br />вниз </p>
            </div>
        </div>
        <div class="news clearfix">
            <div class="news-title">
                <p>
                    <span id="textspan8">Новости<br /></span><span id="textspan9">будь в курсе всех событий</span>
                </p>
            </div>
            <div class="news-block clearfix">
                <div class="new">
                    <p>
                        <a href="#" class="new-title">Туроператор &quot;OpenGeorgia&quot;<br /></a>
                        <span class="new-date">11.02.2015<br /></span>
                        <span class="new-content">Мы являемся первым профильным туристическим оператором по Грузии в Украине.</span>
                    </p>
                </div>
                <div class="new">
                    <p>
                        <a href="#" class="new-title">Туроператор &quot;OpenGeorgia&quot;<br /></a>
                        <span class="new-date">11.02.2015<br /></span>
                        <span class="new-content">Мы являемся первым профильным туристическим оператором по Грузии в Украине.</span>
                    </p>
                </div>
                <div class="new">
                    <p>
                        <a href="#" class="new-title">Туроператор &quot;OpenGeorgia&quot;<br /></a>
                        <span class="new-date">11.02.2015<br /></span>
                        <span class="new-content">Мы являемся первым профильным туристическим оператором по Грузии в Украине.</span>
                    </p>
                </div>
                <div class="new">
                    <p>
                        <a href="#" class="new-title">Туроператор &quot;OpenGeorgia&quot;<br /></a>
                        <span class="new-date">11.02.2015<br /></span>
                        <span class="new-content">Мы являемся первым профильным туристическим оператором по Грузии в Украине.</span>
                    </p>
                </div>
            </div>
        </div>
        <div class="groups-bg clearfix">
            <div class="groups clearfix">
                <div class="groupLinks">
                    <span id="textspan30">Туры&#x3a;</span>
                    <a href="#" class="groupLink">гастрономические</a>
                    <a href="#" class="groupLink">развлечения</a>
                    <a href="#" class="groupLink">шопинг</a>
                </div>
                <div class="middleHelper"></div>
            </div>
            <div class="centerbox clearfix">
                <p class="consultLinks">
                    Вы можете обратиться к нашему консультанту для
                    <a href="#" class="link-btn"> подбора&nbsp;тура </a> или воспользоваться
                    <a href="#" class="link-btn"> поиском </a>
                </p>
            </div>
        </div>
}
<div>
    @{Html.RenderAction("TourForHight");}
    <hr>
    @{Html.RenderAction("Center");}
    <hr>
    @{Html.RenderAction("TourForDown");}
    <hr>
</div>

WorkWithKOTE/Views/Home/TourForDown.cshtml
@model IEnumerable<WorkWithKOTE.Models.Tour>
@foreach (var item in Model)
{
    @Html.DisplayFor(m => item.NameTour)<br />
    <img src="@Html.DisplayFor(m=>item.TourImg)" width="50px" height="75px" />
    Html.RenderAction("DateForCurrentTour", new { id = item.TourId });<br />
    @Html.ActionLink("Посмотреть детали тура", "Index", "TourDisplay", new { id = item.TourId }, null)<br />
    <input type="button" value="Оплатить тур" onclick="location.href='@Url.Action("Index", "Buy", new {id=item.TourId })'" />

}

WorkWithKOTE/Views/Home/TourForHight.cshtml
@model IEnumerable<WorkWithKOTE.Models.Tour>
    @foreach(var item in Model)
    {
        @Html.DisplayFor(m=>item.NameTour)<br/>
        <img src="@Html.DisplayFor(m=>item.TourImg)" width="50px" height="75px"/>
        Html.RenderAction("DateForCurrentTour", new { id = item.TourId });<br/>
        @Html.ActionLink("Посмотреть детали тура", "Index", "TourDisplay", new { id = item.TourId },null)<br/>
       <input type="button" value="Оплатить тур" onclick="location.href='@Url.Action("Index", "Buy", new {id=item.TourId })'"/>
       
    }